lsi: false
safe: true
source: https://github.com/mikh-maksi/python-bot-materials/blob/main/day01/message01/
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
markdown: kramdown
